project:
  type: website
  output-dir: docs

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Project overview"
      - href: data_analysis.ipynb
        text: "Data Preparation, EDA, & ML Models"
      - href: Visualizations.qmd
        text: "EDA Visualizations"
      - href: career_plan.qmd
        text: "Skills Gap & Career Strategy"
format:
  html:
    theme: cosmo
    toc: true